### ISSUE TITLE
Confirm the final .rsf files for MoJoFM metric calculation.

### ISSUE THREAD

**Issue by mi-lee** [resess/2019_microservice_extraction#9]
@ljkirby  and I found that running mojofm on PartsUnlimitedMRP produced 69.44% but this is an old version (i.e. here: https://github.com/resess/2019_microservice_extraction/tree/master/impl/architechtureFiles/PartsUnlimited). 

@suiyoubi , do you think you could upload the newest .rsf file (and any others that you may not have added)?

Once we do this, we can continue on with the analysis of fosci/bunch results.

**Comment by ljkirby** [comment]
Bunch rsf file for PartsUnlimitedMRP was updated in commit cbd14fc26239445f2ec34e5e61fc4c9aa21b93bd -- thanks @suiyoubi !
